import type {
  Inspection,
  ExtractedField,
  ComplianceCheck,
  Violation,
} from "@/lib/types";

// ──────────────────────────────────────────────
// Shared extracted fields for mock inspections
// ──────────────────────────────────────────────

const riceFields: ExtractedField[] = [
  { label: "Product Name", value: "Basmati Rice Premium", status: "detected", confidence: 97 },
  { label: "Brand", value: "India Gate", status: "detected", confidence: 96 },
  { label: "Category", value: "Food & Beverages", status: "detected", confidence: 95 },
  { label: "Manufacturer / Packer", value: "KRBL Limited", status: "detected", confidence: 94 },
  { label: "Address", value: "5190, Lahori Gate, Delhi - 110006", status: "detected", confidence: 92 },
  { label: "Country of Origin", value: "India", status: "detected", confidence: 99 },
  { label: "Net Quantity", value: "5 kg", status: "detected", confidence: 98 },
  { label: "MRP", value: "₹385 (Inclusive of all taxes)", status: "detected", confidence: 97 },
  { label: "Manufacturing Date", value: "October 2024", status: "detected", confidence: 91 },
  { label: "Best Before", value: "24 months from packing", status: "detected", confidence: 90 },
  { label: "Consumer Care", value: "1800-XXX-XXXX | care@krbl.in", status: "detected", confidence: 88 },
  { label: "Unit Sale Price", value: "₹77 per kg", status: "detected", confidence: 85 },
  { label: "FSSAI License", value: "10013022000025", status: "detected", confidence: 93 },
  { label: "Batch / Lot Number", value: "BT-OCT24-05", status: "detected", confidence: 87 },
];

const biscuitFields: ExtractedField[] = [
  { label: "Product Name", value: "Good Day Cashew Cookies", status: "detected", confidence: 96 },
  { label: "Brand", value: "Britannia", status: "detected", confidence: 99 },
  { label: "Category", value: "Packaged Snacks", status: "detected", confidence: 95 },
  { label: "Manufacturer / Packer", value: "Britannia Industries Limited", status: "detected", confidence: 97 },
  { label: "Address", value: "5/1A, Hungerford Street, Kolkata - 700017", status: "detected", confidence: 93 },
  { label: "Country of Origin", value: "India", status: "detected", confidence: 99 },
  { label: "Net Quantity", value: "200 g", status: "detected", confidence: 98 },
  { label: "MRP", value: "₹40 (Inclusive of all taxes)", status: "detected", confidence: 97 },
  { label: "Manufacturing Date", value: "August 2024", status: "detected", confidence: 92 },
  { label: "Best Before", value: "6 months from manufacturing", status: "detected", confidence: 91 },
  { label: "Consumer Care", value: "1860-XXX-XXXX", status: "detected", confidence: 89 },
  { label: "Unit Sale Price", value: null, status: "missing", confidence: 0 },
  { label: "FSSAI License", value: "10013022000031", status: "detected", confidence: 94 },
  { label: "Batch / Lot Number", value: "BT-AUG24-11", status: "detected", confidence: 88 },
];

const oilFields: ExtractedField[] = [
  { label: "Product Name", value: "Refined Sunflower Oil", status: "detected", confidence: 95 },
  { label: "Brand", value: "Fortune", status: "detected", confidence: 97 },
  { label: "Category", value: "Edible Oils", status: "detected", confidence: 96 },
  { label: "Manufacturer / Packer", value: "Adani Wilmar Limited", status: "detected", confidence: 96 },
  { label: "Address", value: "Shantigram, Nr. Vaishnodevi Circle, S.G. Highway, Ahmedabad 382421", status: "detected", confidence: 90 },
  { label: "Country of Origin", value: null, status: "missing", confidence: 0 },
  { label: "Net Quantity", value: "1 L", status: "detected", confidence: 98 },
  { label: "MRP", value: "₹140 (Inclusive of all taxes)", status: "detected", confidence: 97 },
  { label: "Manufacturing Date", value: "September 2024", status: "needs_review", confidence: 55 },
  { label: "Best Before", value: "18 months from packing", status: "detected", confidence: 89 },
  { label: "Consumer Care", value: "1800-XXX-XXXX", status: "detected", confidence: 86 },
  { label: "Unit Sale Price", value: "₹140 per litre", status: "detected", confidence: 87 },
  { label: "FSSAI License", value: "10016011001726", status: "detected", confidence: 93 },
  { label: "Batch / Lot Number", value: "BT-SEP24-22", status: "needs_review", confidence: 60 },
];

const shampooFields: ExtractedField[] = [
  { label: "Product Name", value: "Anti-Dandruff Shampoo", status: "detected", confidence: 96 },
  { label: "Brand", value: "Head & Shoulders", status: "detected", confidence: 98 },
  { label: "Category", value: "Personal Care", status: "detected", confidence: 97 },
  { label: "Manufacturer / Packer", value: "Procter & Gamble Home Products Pvt Ltd", status: "detected", confidence: 95 },
  { label: "Address", value: "Plant 17, Goa Industrial Estate, Goa 403722", status: "detected", confidence: 91 },
  { label: "Country of Origin", value: "India", status: "detected", confidence: 99 },
  { label: "Net Quantity", value: "340 ml", status: "detected", confidence: 97 },
  { label: "MRP", value: "₹299 (Inclusive of all taxes)", status: "detected", confidence: 98 },
  { label: "Manufacturing Date", value: null, status: "missing", confidence: 0 },
  { label: "Best Before", value: "36 months from manufacture", status: "detected", confidence: 88 },
  { label: "Consumer Care", value: "1800-22-4444 | www.pg.com/in", status: "detected", confidence: 87 },
  { label: "Unit Sale Price", value: null, status: "missing", confidence: 0 },
  { label: "Batch / Lot Number", value: "7340 B", status: "detected", confidence: 85 },
];

const snackFields: ExtractedField[] = [
  { label: "Product Name", value: "Aloo Bhujia", status: "detected", confidence: 97 },
  { label: "Brand", value: "Haldiram's", status: "detected", confidence: 99 },
  { label: "Category", value: "Packaged Snacks", status: "detected", confidence: 96 },
  { label: "Manufacturer / Packer", value: "Haldiram Foods International Pvt Ltd", status: "detected", confidence: 96 },
  { label: "Address", value: "Bhuj Road, Baroda - 391 440", status: "needs_review", confidence: 62 },
  { label: "Country of Origin", value: "India", status: "detected", confidence: 99 },
  { label: "Net Quantity", value: "400 g", status: "detected", confidence: 98 },
  { label: "MRP", value: "₹99 (Inclusive of all taxes)", status: "detected", confidence: 97 },
  { label: "Manufacturing Date", value: "July 2024", status: "detected", confidence: 93 },
  { label: "Best Before", value: "90 days from manufacture", status: "detected", confidence: 91 },
  { label: "Consumer Care", value: "1800-XXX-XXXX", status: "detected", confidence: 86 },
  { label: "Unit Sale Price", value: null, status: "missing", confidence: 0 },
  { label: "FSSAI License", value: "10012042000032", status: "detected", confidence: 94 },
  { label: "Batch / Lot Number", value: "HF-JUL24-38", status: "detected", confidence: 89 },
];

// ──────────────────────────────────────────────
// Compliance Checks
// ──────────────────────────────────────────────

const riceCompliance: ComplianceCheck[] = [
  { id: "c1", requirement: "Product Name", field: "Product Name", value: "Basmati Rice Premium", status: "pass", rule: "Rule 6(1)(a)", detail: "Product name prominently declared" },
  { id: "c2", requirement: "Net Quantity", field: "Net Quantity", value: "5 kg", status: "pass", rule: "Rule 6(1)(b)", detail: "Net quantity declared in standard unit" },
  { id: "c3", requirement: "MRP Declaration", field: "MRP", value: "₹385", status: "pass", rule: "Rule 6(1)(d)", detail: "MRP declared with tax inclusion note" },
  { id: "c4", requirement: "Manufacturer/Packer Details", field: "Manufacturer / Packer", value: "KRBL Limited", status: "pass", rule: "Rule 6(1)(c)", detail: "Manufacturer name and address present" },
  { id: "c5", requirement: "Country of Origin", field: "Country of Origin", value: "India", status: "pass", rule: "Rule 6(1)(e)", detail: "Country of origin declared" },
  { id: "c6", requirement: "Manufacturing Date", field: "Manufacturing Date", value: "October 2024", status: "pass", rule: "Rule 6(1)(f)", detail: "Manufacturing date present" },
  { id: "c7", requirement: "Consumer Care Details", field: "Consumer Care", value: "1800-XXX-XXXX", status: "pass", rule: "Rule 6(1)(g)", detail: "Consumer care contact present" },
  { id: "c8", requirement: "Unit Sale Price", field: "Unit Sale Price", value: "₹77 per kg", status: "pass", rule: "Rule 6(1)(h)", detail: "Unit sale price declared for commodities sold by weight" },
];

const biscuitCompliance: ComplianceCheck[] = [
  { id: "c1", requirement: "Product Name", field: "Product Name", value: "Good Day Cashew Cookies", status: "pass", rule: "Rule 6(1)(a)" },
  { id: "c2", requirement: "Net Quantity", field: "Net Quantity", value: "200 g", status: "pass", rule: "Rule 6(1)(b)" },
  { id: "c3", requirement: "MRP Declaration", field: "MRP", value: "₹40", status: "pass", rule: "Rule 6(1)(d)" },
  { id: "c4", requirement: "Manufacturer/Packer Details", field: "Manufacturer / Packer", value: "Britannia Industries Limited", status: "pass", rule: "Rule 6(1)(c)" },
  { id: "c5", requirement: "Country of Origin", field: "Country of Origin", value: "India", status: "pass", rule: "Rule 6(1)(e)" },
  { id: "c6", requirement: "Manufacturing Date", field: "Manufacturing Date", value: "August 2024", status: "pass", rule: "Rule 6(1)(f)" },
  { id: "c7", requirement: "Best Before/Expiry", field: "Best Before", value: "6 months", status: "pass", rule: "Rule 6(1)(f)" },
  { id: "c8", requirement: "Consumer Care Details", field: "Consumer Care", value: "Present", status: "pass", rule: "Rule 6(1)(g)" },
  { id: "c9", requirement: "Unit Sale Price (>100g)", field: "Unit Sale Price", value: "Not declared", status: "fail", rule: "Rule 6(1)(h)", detail: "Unit sale price not declared for net content > 100g" },
];

const oilCompliance: ComplianceCheck[] = [
  { id: "c1", requirement: "Product Name", field: "Product Name", value: "Refined Sunflower Oil", status: "pass", rule: "Rule 6(1)(a)" },
  { id: "c2", requirement: "Net Quantity", field: "Net Quantity", value: "1 L", status: "pass", rule: "Rule 6(1)(b)" },
  { id: "c3", requirement: "MRP Declaration", field: "MRP", value: "₹140", status: "pass", rule: "Rule 6(1)(d)" },
  { id: "c4", requirement: "Manufacturer/Packer Details", field: "Manufacturer / Packer", value: "Adani Wilmar Limited", status: "pass", rule: "Rule 6(1)(c)" },
  { id: "c5", requirement: "Country of Origin", field: "Country of Origin", value: "Not found", status: "fail", rule: "Rule 6(1)(e)", detail: "Country of origin not detected on label" },
  { id: "c6", requirement: "Manufacturing Date", field: "Manufacturing Date", value: "Partially visible", status: "needs_review", rule: "Rule 6(1)(f)", detail: "Manufacturing date partially legible — inspector verification needed" },
  { id: "c7", requirement: "Best Before/Expiry", field: "Best Before", value: "18 months", status: "pass", rule: "Rule 6(1)(f)" },
  { id: "c8", requirement: "Consumer Care Details", field: "Consumer Care", value: "Present", status: "pass", rule: "Rule 6(1)(g)" },
  { id: "c9", requirement: "FSSAI License (Food Products)", field: "FSSAI License", value: "Present", status: "pass", rule: "FSS Act 2006" },
];

const shampooCompliance: ComplianceCheck[] = [
  { id: "c1", requirement: "Product Name", field: "Product Name", value: "Anti-Dandruff Shampoo", status: "pass", rule: "Rule 6(1)(a)" },
  { id: "c2", requirement: "Net Quantity", field: "Net Quantity", value: "340 ml", status: "pass", rule: "Rule 6(1)(b)" },
  { id: "c3", requirement: "MRP Declaration", field: "MRP", value: "₹299", status: "pass", rule: "Rule 6(1)(d)" },
  { id: "c4", requirement: "Manufacturer/Packer Details", field: "Manufacturer / Packer", value: "Present", status: "pass", rule: "Rule 6(1)(c)" },
  { id: "c5", requirement: "Country of Origin", field: "Country of Origin", value: "India", status: "pass", rule: "Rule 6(1)(e)" },
  { id: "c6", requirement: "Manufacturing Date", field: "Manufacturing Date", value: "Not found", status: "fail", rule: "Rule 6(1)(f)", detail: "Manufacturing date not detected on label" },
  { id: "c7", requirement: "Best Before/Expiry", field: "Best Before", value: "36 months", status: "pass", rule: "Rule 6(1)(f)" },
  { id: "c8", requirement: "Consumer Care Details", field: "Consumer Care", value: "Present", status: "pass", rule: "Rule 6(1)(g)" },
];

// ──────────────────────────────────────────────
// Violations
// ──────────────────────────────────────────────

const biscuitViolations: Violation[] = [
  {
    id: "v1",
    type: "Missing Declaration",
    requirement: "Unit Sale Price for commodities exceeding 100 g net content",
    issue: "Unit Sale Price not declared on label",
    field: "Unit Sale Price",
    evidence: "Label inspection — field absent. Net content 200 g exceeds 100 g threshold.",
    severity: "medium",
    explanation: "Under Rule 6(1)(h) of the Legal Metrology (Packaged Commodities) Rules 2011, commodities sold by weight/volume with net content exceeding 100 g must declare the unit sale price. The label of Good Day Cashew Cookies (200 g) does not carry a unit sale price declaration.",
  },
];

const oilViolations: Violation[] = [
  {
    id: "v1",
    type: "Missing Declaration",
    requirement: "Country of Origin mandatory for all packaged commodities",
    issue: "Country of Origin not found on label",
    field: "Country of Origin",
    evidence: "AI scan of all visible label areas. Field absent.",
    severity: "high",
    explanation: "Rule 6(1)(e) mandates the declaration of Country of Origin on all packaged commodities. The label of Fortune Refined Sunflower Oil (1 L) does not carry this declaration.",
  },
  {
    id: "v2",
    type: "Illegible Declaration",
    requirement: "Manufacturing/Packing date must be clearly printed",
    issue: "Manufacturing date partially visible — possibly overprinted or faded",
    field: "Manufacturing Date",
    evidence: "Partially readable date detected — insufficient for compliance verification.",
    severity: "medium",
    explanation: "Rule 6(1)(f) requires the manufacturing/packing date to be clearly and legibly printed. The detected manufacturing date was partially readable. Inspector should physically verify the label.",
  },
];

const shampooViolations: Violation[] = [
  {
    id: "v1",
    type: "Missing Declaration",
    requirement: "Manufacturing/Packing date must be declared",
    issue: "Manufacturing date not found on label",
    field: "Manufacturing Date",
    evidence: "Full label scan — manufacturing date field absent.",
    severity: "medium",
    explanation: "Rule 6(1)(f) of Legal Metrology (Packaged Commodities) Rules 2011 mandates declaration of the month and year of manufacturing/packing. The label of Head & Shoulders Anti-Dandruff Shampoo (340 ml) does not carry a manufacturing date.",
  },
];

const snackViolations: Violation[] = [
  {
    id: "v1",
    type: "Needs Verification",
    requirement: "Manufacturer address must be complete and verifiable",
    issue: "Address detected with low confidence — possibly abbreviated",
    field: "Address",
    evidence: "Detected address: 'Bhuj Road, Baroda - 391 440' — possibly incomplete.",
    severity: "low",
    explanation: "Rule 6(1)(c) requires the complete address of the manufacturer/packer. The detected address appears abbreviated. Inspector should verify the full address against FSSAI records.",
  },
];

// ──────────────────────────────────────────────
// INSPECTIONS MOCK DATA
// ──────────────────────────────────────────────

export const mockInspections: Inspection[] = [
  {
    id: "INS-2024-0091",
    product: {
      name: "Basmati Rice Premium",
      brand: "India Gate",
      category: "Food & Beverages",
      manufacturer: "KRBL Limited",
      address: "5190, Lahori Gate, Delhi - 110006",
      countryOfOrigin: "India",
      netQuantity: "5 kg",
      mrp: "₹385",
      manufacturingDate: "October 2024",
      bestBefore: "24 months from packing",
      consumerCare: "1800-XXX-XXXX | care@krbl.in",
      unitSalePrice: "₹77 per kg",
      fssaiLicense: "10013022000025",
      batchNumber: "BT-OCT24-05",
    },
    result: "compliant",
    verificationStatus: "verified",
    extractedFields: riceFields,
    complianceChecks: riceCompliance,
    violations: [],
    verification: {
      decision: "compliant",
      remarks: "All mandatory declarations present and legible. Product complies with Legal Metrology (Packaged Commodities) Rules 2011.",
      verifiedAt: "2024-11-02T10:45:00Z",
      inspectorId: "INS-DL-042",
      inspectorName: "Rajesh Kumar",
    },
    createdAt: "2024-11-02T10:15:00Z",
    updatedAt: "2024-11-02T10:45:00Z",
    inspectorId: "INS-DL-042",
    inspectorName: "Rajesh Kumar",
    imageFileName: "india_gate_rice_5kg.jpg",
    reportId: "RPT-2024-0091",
  },
  {
    id: "INS-2024-0090",
    product: {
      name: "Good Day Cashew Cookies",
      brand: "Britannia",
      category: "Packaged Snacks",
      manufacturer: "Britannia Industries Limited",
      address: "5/1A, Hungerford Street, Kolkata - 700017",
      countryOfOrigin: "India",
      netQuantity: "200 g",
      mrp: "₹40",
      manufacturingDate: "August 2024",
      bestBefore: "6 months from manufacturing",
      consumerCare: "1860-XXX-XXXX",
      unitSalePrice: null,
      fssaiLicense: "10013022000031",
      batchNumber: "BT-AUG24-11",
    },
    result: "potential_violation",
    verificationStatus: "confirmed_violation",
    extractedFields: biscuitFields,
    complianceChecks: biscuitCompliance,
    violations: biscuitViolations,
    verification: {
      decision: "confirmed_violation",
      remarks: "Unit sale price not declared despite net content exceeding 100 g threshold. Formal notice issued.",
      verifiedAt: "2024-11-01T15:30:00Z",
      inspectorId: "INS-DL-042",
      inspectorName: "Rajesh Kumar",
    },
    createdAt: "2024-11-01T14:30:00Z",
    updatedAt: "2024-11-01T15:30:00Z",
    inspectorId: "INS-DL-042",
    inspectorName: "Rajesh Kumar",
    imageFileName: "britannia_good_day_200g.jpg",
    reportId: "RPT-2024-0090",
  },
  {
    id: "INS-2024-0089",
    product: {
      name: "Refined Sunflower Oil",
      brand: "Fortune",
      category: "Edible Oils",
      manufacturer: "Adani Wilmar Limited",
      address: "Shantigram, Nr. Vaishnodevi Circle, S.G. Highway, Ahmedabad 382421",
      countryOfOrigin: null,
      netQuantity: "1 L",
      mrp: "₹140",
      manufacturingDate: "September 2024",
      bestBefore: "18 months from packing",
      consumerCare: "1800-XXX-XXXX",
      unitSalePrice: "₹140 per litre",
      fssaiLicense: "10016011001726",
      batchNumber: "BT-SEP24-22",
    },
    result: "potential_violation",
    verificationStatus: "pending",
    extractedFields: oilFields,
    complianceChecks: oilCompliance,
    violations: oilViolations,
    createdAt: "2024-10-31T09:00:00Z",
    updatedAt: "2024-10-31T09:30:00Z",
    inspectorId: "INS-MH-017",
    inspectorName: "Priya Sharma",
    imageFileName: "fortune_sunflower_oil_1l.jpg",
    reportId: "RPT-2024-0089",
  },
  {
    id: "INS-2024-0088",
    product: {
      name: "Anti-Dandruff Shampoo",
      brand: "Head & Shoulders",
      category: "Personal Care",
      manufacturer: "Procter & Gamble Home Products Pvt Ltd",
      address: "Plant 17, Goa Industrial Estate, Goa 403722",
      countryOfOrigin: "India",
      netQuantity: "340 ml",
      mrp: "₹299",
      manufacturingDate: null,
      bestBefore: "36 months from manufacture",
      consumerCare: "1800-22-4444 | www.pg.com/in",
      unitSalePrice: null,
      batchNumber: "7340 B",
    },
    result: "potential_violation",
    verificationStatus: "further_review",
    extractedFields: shampooFields,
    complianceChecks: shampooCompliance,
    violations: shampooViolations,
    verification: {
      decision: "further_review",
      remarks: "Physical label inspection required to confirm manufacturing date. Sample retained.",
      verifiedAt: "2024-10-30T16:00:00Z",
      inspectorId: "INS-MH-017",
      inspectorName: "Priya Sharma",
    },
    createdAt: "2024-10-30T14:00:00Z",
    updatedAt: "2024-10-30T16:00:00Z",
    inspectorId: "INS-MH-017",
    inspectorName: "Priya Sharma",
    imageFileName: "head_shoulders_340ml.jpg",
    reportId: "RPT-2024-0088",
  },
  {
    id: "INS-2024-0087",
    product: {
      name: "Aloo Bhujia",
      brand: "Haldiram's",
      category: "Packaged Snacks",
      manufacturer: "Haldiram Foods International Pvt Ltd",
      address: "Bhuj Road, Baroda - 391 440",
      countryOfOrigin: "India",
      netQuantity: "400 g",
      mrp: "₹99",
      manufacturingDate: "July 2024",
      bestBefore: "90 days from manufacture",
      consumerCare: "1800-XXX-XXXX",
      unitSalePrice: null,
      fssaiLicense: "10012042000032",
      batchNumber: "HF-JUL24-38",
    },
    result: "needs_review",
    verificationStatus: "pending",
    extractedFields: snackFields,
    complianceChecks: [
      { id: "c1", requirement: "Product Name", field: "Product Name", value: "Aloo Bhujia", status: "pass", rule: "Rule 6(1)(a)" },
      { id: "c2", requirement: "Net Quantity", field: "Net Quantity", value: "400 g", status: "pass", rule: "Rule 6(1)(b)" },
      { id: "c3", requirement: "MRP Declaration", field: "MRP", value: "₹99", status: "pass", rule: "Rule 6(1)(d)" },
      { id: "c4", requirement: "Manufacturer/Packer Details", field: "Address", value: "Partially legible", status: "needs_review", rule: "Rule 6(1)(c)", detail: "Address may be abbreviated" },
      { id: "c5", requirement: "Country of Origin", field: "Country of Origin", value: "India", status: "pass", rule: "Rule 6(1)(e)" },
      { id: "c6", requirement: "Manufacturing Date", field: "Manufacturing Date", value: "July 2024", status: "pass", rule: "Rule 6(1)(f)" },
      { id: "c7", requirement: "Best Before/Expiry", field: "Best Before", value: "90 days", status: "pass", rule: "Rule 6(1)(f)" },
      { id: "c8", requirement: "Consumer Care Details", field: "Consumer Care", value: "Present", status: "pass", rule: "Rule 6(1)(g)" },
    ],
    violations: snackViolations,
    createdAt: "2024-10-29T11:00:00Z",
    updatedAt: "2024-10-29T11:30:00Z",
    inspectorId: "INS-GJ-009",
    inspectorName: "Amit Patel",
    imageFileName: "haldirams_aloo_bhujia_400g.jpg",
  },
  {
    id: "INS-2024-0086",
    product: {
      name: "Toor Dal",
      brand: "Tata Sampann",
      category: "Food & Beverages",
      manufacturer: "Tata Consumer Products Limited",
      address: "11, Floor, Tower 2, One World Centre, Jupiter Mills Compound, 841, Senapati Bapat Marg, Lower Parel, Mumbai 400 013",
      countryOfOrigin: "India",
      netQuantity: "1 kg",
      mrp: "₹190",
      manufacturingDate: "September 2024",
      bestBefore: "12 months from packaging",
      consumerCare: "1800-XXX-XXXX",
      unitSalePrice: "₹190 per kg",
      fssaiLicense: "10013022001234",
      batchNumber: "TS-SEP24-01",
    },
    result: "compliant",
    verificationStatus: "verified",
    extractedFields: [
      { label: "Product Name", value: "Toor Dal", status: "detected", confidence: 97 },
      { label: "Brand", value: "Tata Sampann", status: "detected", confidence: 99 },
      { label: "Category", value: "Food & Beverages", status: "detected", confidence: 95 },
      { label: "Manufacturer / Packer", value: "Tata Consumer Products Limited", status: "detected", confidence: 96 },
      { label: "Address", value: "Mumbai 400 013", status: "detected", confidence: 90 },
      { label: "Country of Origin", value: "India", status: "detected", confidence: 99 },
      { label: "Net Quantity", value: "1 kg", status: "detected", confidence: 98 },
      { label: "MRP", value: "₹190 (Inclusive of all taxes)", status: "detected", confidence: 97 },
      { label: "Manufacturing Date", value: "September 2024", status: "detected", confidence: 93 },
      { label: "Best Before", value: "12 months from packaging", status: "detected", confidence: 91 },
      { label: "Consumer Care", value: "1800-XXX-XXXX", status: "detected", confidence: 87 },
      { label: "Unit Sale Price", value: "₹190 per kg", status: "detected", confidence: 85 },
      { label: "FSSAI License", value: "10013022001234", status: "detected", confidence: 94 },
    ],
    complianceChecks: [
      { id: "c1", requirement: "Product Name", field: "Product Name", value: "Toor Dal", status: "pass", rule: "Rule 6(1)(a)" },
      { id: "c2", requirement: "Net Quantity", field: "Net Quantity", value: "1 kg", status: "pass", rule: "Rule 6(1)(b)" },
      { id: "c3", requirement: "MRP Declaration", field: "MRP", value: "₹190", status: "pass", rule: "Rule 6(1)(d)" },
      { id: "c4", requirement: "Manufacturer/Packer Details", field: "Manufacturer / Packer", value: "Present", status: "pass", rule: "Rule 6(1)(c)" },
      { id: "c5", requirement: "Country of Origin", field: "Country of Origin", value: "India", status: "pass", rule: "Rule 6(1)(e)" },
      { id: "c6", requirement: "Manufacturing Date", field: "Manufacturing Date", value: "September 2024", status: "pass", rule: "Rule 6(1)(f)" },
      { id: "c7", requirement: "Best Before/Expiry", field: "Best Before", value: "12 months", status: "pass", rule: "Rule 6(1)(f)" },
      { id: "c8", requirement: "Consumer Care Details", field: "Consumer Care", value: "Present", status: "pass", rule: "Rule 6(1)(g)" },
      { id: "c9", requirement: "Unit Sale Price", field: "Unit Sale Price", value: "₹190 per kg", status: "pass", rule: "Rule 6(1)(h)" },
    ],
    violations: [],
    verification: {
      decision: "compliant",
      remarks: "All required declarations present. Package fully compliant.",
      verifiedAt: "2024-10-28T12:00:00Z",
      inspectorId: "INS-MH-017",
      inspectorName: "Priya Sharma",
    },
    createdAt: "2024-10-28T11:00:00Z",
    updatedAt: "2024-10-28T12:00:00Z",
    inspectorId: "INS-MH-017",
    inspectorName: "Priya Sharma",
    imageFileName: "tata_sampann_toor_dal_1kg.jpg",
    reportId: "RPT-2024-0086",
  },
];
