import type { Report } from "@/lib/types";

export const mockReports: Report[] = [
  {
    id: "RPT-2024-0091",
    inspectionId: "INS-2024-0091",
    product: "Basmati Rice Premium — India Gate (5 kg)",
    category: "Food & Beverages",
    result: "compliant",
    verificationStatus: "verified",
    generatedAt: "2024-11-02T10:45:00Z",
    inspectorName: "Rajesh Kumar",
  },
  {
    id: "RPT-2024-0090",
    inspectionId: "INS-2024-0090",
    product: "Good Day Cashew Cookies — Britannia (200 g)",
    category: "Packaged Snacks",
    result: "potential_violation",
    verificationStatus: "confirmed_violation",
    generatedAt: "2024-11-01T15:30:00Z",
    inspectorName: "Rajesh Kumar",
  },
  {
    id: "RPT-2024-0089",
    inspectionId: "INS-2024-0089",
    product: "Refined Sunflower Oil — Fortune (1 L)",
    category: "Edible Oils",
    result: "potential_violation",
    verificationStatus: "pending",
    generatedAt: "2024-10-31T09:30:00Z",
    inspectorName: "Priya Sharma",
  },
  {
    id: "RPT-2024-0088",
    inspectionId: "INS-2024-0088",
    product: "Anti-Dandruff Shampoo — Head & Shoulders (340 ml)",
    category: "Personal Care",
    result: "potential_violation",
    verificationStatus: "further_review",
    generatedAt: "2024-10-30T16:00:00Z",
    inspectorName: "Priya Sharma",
  },
  {
    id: "RPT-2024-0086",
    inspectionId: "INS-2024-0086",
    product: "Toor Dal — Tata Sampann (1 kg)",
    category: "Food & Beverages",
    result: "compliant",
    verificationStatus: "verified",
    generatedAt: "2024-10-28T12:00:00Z",
    inspectorName: "Priya Sharma",
  },
];
