import type { ComplianceRequirement } from "@/lib/types";

export const complianceRules: ComplianceRequirement[] = [
  // Product Identification
  {
    id: "R-01",
    category: "Product Identification",
    name: "Product / Generic Name",
    explanation: "Every package must carry the generic or common name of the commodity in addition to the brand name. This helps consumers identify the actual product beyond marketing names.",
    applicableField: "Product Name",
    example: "'Basmati Rice', 'Refined Sunflower Oil', 'Detergent Powder'",
    ruleReference: "Rule 6(1)(a) — LMPC Rules 2011",
    mandatory: true,
  },
  // Manufacturer/Packer/Importer
  {
    id: "R-02",
    category: "Manufacturer / Packer / Importer",
    name: "Name & Complete Address",
    explanation: "The full name and postal address of the manufacturer, packer, or importer must be declared. P.O. Box numbers are not acceptable as a substitute for the complete address.",
    applicableField: "Manufacturer / Packer / Address",
    example: "KRBL Limited, 5190, Lahori Gate, Delhi - 110006",
    ruleReference: "Rule 6(1)(c) — LMPC Rules 2011",
    mandatory: true,
  },
  // Country of Origin
  {
    id: "R-03",
    category: "Country of Origin",
    name: "Country of Origin Declaration",
    explanation: "Every package must declare the country of origin. For products manufactured in India, the declaration 'Made in India' or 'Country of Origin: India' satisfies this requirement.",
    applicableField: "Country of Origin",
    example: "Made in India / Country of Origin: India",
    ruleReference: "Rule 6(1)(e) — LMPC Rules 2011",
    mandatory: true,
  },
  // Net Quantity
  {
    id: "R-04",
    category: "Net Quantity",
    name: "Net Quantity in Standard Units",
    explanation: "Net quantity must be declared in the metric system (grams, kilograms, millilitres, litres). The quantity printed on the label must match the actual contents within permissible error limits.",
    applicableField: "Net Quantity",
    example: "500 g / 1 kg / 200 ml / 1 L",
    ruleReference: "Rule 6(1)(b) — LMPC Rules 2011",
    mandatory: true,
  },
  {
    id: "R-05",
    category: "Net Quantity",
    name: "Minimum Height of Numerals",
    explanation: "The numerals used in declaring net quantity must meet minimum height requirements based on the net content of the package to ensure legibility.",
    applicableField: "Net Quantity",
    example: "Numeral height ≥ 2mm for packages ≤ 200g/ml; ≥ 4mm for packages up to 1kg/litre",
    ruleReference: "Schedule II — LMPC Rules 2011",
    mandatory: true,
  },
  // MRP
  {
    id: "R-06",
    category: "MRP",
    name: "Maximum Retail Price (MRP)",
    explanation: "MRP must be declared as 'Maximum Retail Price (inclusive of all taxes)' or 'MRP (Incl. of all taxes)'. Sale above the declared MRP is a legal offence.",
    applicableField: "MRP",
    example: "MRP: ₹120 (Inclusive of all taxes)",
    ruleReference: "Rule 6(1)(d) — LMPC Rules 2011",
    mandatory: true,
  },
  // Date Declarations
  {
    id: "R-07",
    category: "Date Declarations",
    name: "Month and Year of Manufacture/Packing",
    explanation: "The month and year of manufacture, packing, or import must be declared. For pre-packaged food products, this is also required by FSSAI regulations.",
    applicableField: "Manufacturing Date",
    example: "Manufactured: October 2024 / Mfg: Oct 2024",
    ruleReference: "Rule 6(1)(f) — LMPC Rules 2011",
    mandatory: true,
  },
  {
    id: "R-08",
    category: "Date Declarations",
    name: "Best Before / Expiry Date",
    explanation: "Perishable and semi-perishable commodities must declare the best before date or expiry date. For many food products this is also required under FSSAI labelling regulations.",
    applicableField: "Best Before",
    example: "Best Before: 6 months from date of manufacture / Expiry: 12/2025",
    ruleReference: "Rule 6(1)(f) read with Rule 6(4) — LMPC Rules 2011",
    mandatory: true,
  },
  // Consumer Care
  {
    id: "R-09",
    category: "Consumer Care",
    name: "Consumer Care Details",
    explanation: "Manufacturers/packers of pre-packaged commodities must provide a consumer care contact number or email address on the label to enable consumer grievance redressal.",
    applicableField: "Consumer Care",
    example: "Consumer Care: 1800-XXX-XXXX / care@brand.in",
    ruleReference: "Rule 6(1)(g) — LMPC Rules 2011 (Amendment 2017)",
    mandatory: true,
  },
  // Unit Sale Price
  {
    id: "R-10",
    category: "Unit Sale Price",
    name: "Unit Sale Price",
    explanation: "Commodities sold by weight or volume with net content exceeding 100 grams or 100 millilitres must declare the unit sale price (price per standard unit). This aids consumer comparison.",
    applicableField: "Unit Sale Price",
    example: "₹77 per kg / ₹140 per litre / ₹5 per 100 g",
    ruleReference: "Rule 6(1)(h) — LMPC Rules 2011",
    mandatory: false,
  },
  // Other Declarations
  {
    id: "R-11",
    category: "Other Applicable Declarations",
    name: "FSSAI License Number (Food Products)",
    explanation: "All pre-packaged food products require the FSSAI licence or registration number of the manufacturer/packer as per the Food Safety and Standards (Labelling and Display) Regulations 2020.",
    applicableField: "FSSAI License",
    example: "FSSAI Lic. No. 10013022000025",
    ruleReference: "FSS (Labelling & Display) Regulations 2020",
    mandatory: true,
  },
  {
    id: "R-12",
    category: "Other Applicable Declarations",
    name: "Batch / Lot Number",
    explanation: "A batch or lot identification number allows traceability of the product to its manufacturing batch for quality control and recall purposes. Required under food safety regulations.",
    applicableField: "Batch / Lot Number",
    example: "Batch No.: BT-OCT24-05 / Lot: L12345",
    ruleReference: "FSS (Labelling & Display) Regulations 2020",
    mandatory: false,
  },
  {
    id: "R-13",
    category: "Product Identification",
    name: "Commodity Specific Declarations",
    explanation: "Certain commodities have additional specific declaration requirements. For example, packaged drinking water must declare the ISI certification mark, and certain food products must declare nutritional information.",
    applicableField: "Category-specific fields",
    example: "Nutritional information table for food products",
    ruleReference: "Schedule — LMPC Rules 2011 & FSSAI Regulations",
    mandatory: false,
  },
];
